<?php session_start() ?>
<?php include 'includes/header.php'; ?>
<?php include 'components/navigation.php'; ?>
<div class="container-fluid d-flex flex-column justify-content-center align-items-center c-hero">
    <h1 class="text-capitalize text-white text-center">Currency</h1>
    <p class="text-white text-center">Get all updates on currency exchange rate in Nigeria</p>
</div>
<div class="container-fluid py-2">
    <div class="container text-end d-<?php echo (isset($_SESSION['user_username'])) ? "block":"none" ?> my-2">
        <a
            href="<?php
                        echo (($_SESSION['user_approval'] == 'approved') &&
    in_array($_SESSION['user_level'], ['aggregator', 'Commodities Brokers', 'Specialized Commodities Dealer', 'Commodities Broker Dealer', 'Commodities Trader'])) ? "aggregator.php":"dashboard.php" ?>"
            class="smfs-5 text-secondary text-decoration-none"><i class="bi bi-house-check-fill"></i> Return to dashboard</a>
    </div>
</div>
<div class="container py-4">
    <div class="px-2 mb-3">
     <h6 class="text-uppercase text-comp mb-2">Exchange Rate (NGN)</h6>
        <p class="smfs-5">
            This rate is autogenerated and prepared by LCFE with data from the CBN website. 
        </p>
    </div>
<div class="px-2">
        <?php
            include 'includes/db.php';

            try {
                $sql = "SELECT * FROM exchange_rates";
                $stmt = $pdo->prepare($sql);
                $stmt->execute();

                $exchange = $stmt->fetchAll(PDO::FETCH_ASSOC);

            } catch (PDOException $e) {
                echo "Error: " . $e->getMessage();
            }
        ?>
        <div class="table-responsive">
        <table id="example" class="table table-striped table-bordered datatable" style="width:100%">
        <thead class="thead-dark">
            <tr>
                <th>Date</th>
                <th>Currency</th>
                <th>Buying</th>
                <th>Central</th>
                <th>Selling</th>
                <th class="text-center">Strength</th>
            </tr>
        </thead>
            <tbody class="col-md-12">
                <?php foreach ($exchange as $exch): ?>
                    <tr style="vertical-align: middle">
                    <td class="col-md-2 my-2 py-2"><?= htmlspecialchars($exch['date-added']) ?></td>
                        <td class="col-md-2 my-2 py-2 text-uppercase"><?= htmlspecialchars($exch['currency']) ?></td>
                        <td class="col-md-2 my-2 py-2"><?= htmlspecialchars($exch['buying']) ?></td>
                        <td class="col-md-2 my-2 py-2"><?= htmlspecialchars($exch['central']) ?></td>
                        <td class="col-md-2 my-2 py-2"><?= htmlspecialchars($exch['selling']) ?></td>
                        <td class="col-md-2 my-2 py-2 text-center">
                            <span class="d-<?= ($exch['pl']=='strong') ? 'block':'none'; ?> text-primary"><i class="bi bi-caret-up-fill"></i></span>
                            <span class="d-<?= ($exch['pl']=='weak') ? 'block':'none'; ?> text-danger" ><i class="bi bi-caret-down-fill"></i></span>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        </div>
    </div>
</div>
<?php include 'includes/footer.php'; ?>