<div class="shadow p-4 rounded d-flex flex-column w-75 mx-auto">
    <div class="px-2">
     <h6 class="text-uppercase text-comp mb-2">Exchange Rate (NGN)</h6>
        <p class="smfs-5">
            This rate is autogenerated and prepared by LCFE with data from the CBN website. 
        </p>
    </div>
    <div class="px-2">
        <?php
            include 'includes/db.php';

            try {
                $sql = "SELECT * FROM exchange_rates LIMIT 8";
                $stmt = $pdo->prepare($sql);
                $stmt->execute();

                $exchange = $stmt->fetchAll(PDO::FETCH_ASSOC);

            } catch (PDOException $e) {
                echo "Error: " . $e->getMessage();
            }
        ?>
        <table class="table">
            <tbody class="col-md-12">
                <?php foreach ($exchange as $exch): ?>
                    <tr style="vertical-align: middle">
                        <td class="col-md-5 my-2 py-2 text-uppercase"><?= htmlspecialchars($exch['currency']) ?></td>
                        <td class="col-md-5 my-2 py-2"><?= htmlspecialchars($exch['selling']) ?></td>
                        <td class="col-md-2 my-2 py-2">
                            <span class="d-<?= ($exch['pl']=='strong') ? 'block':'none'; ?> text-primary"><i class="bi bi-caret-up-fill"></i></span>
                            <span class="d-<?= ($exch['pl']=='weak') ? 'block':'none'; ?> text-danger" ><i class="bi bi-caret-down-fill"></i></span>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="text-comp smfs-6 text-end px-2"><a href="currency.php" class="text-comp text-decoration-none"><em>Check more</em></a></div>
</div>